server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:~/pedidos
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      key-serializer : org.apache.kafka.common.serialization.StringSerializer
      value-serializer : org.springframework.kafka.support.serializer.JsonSerializer
      client-id: pedidos
      topic:
        novo-pedido: PEDIDO_NOVO
        pedido-cancelado: PEDIDO_CANCELADO
management:
  health:
    diskSpace:
      enabled: false
    ping:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, scheduledtasks